### ISSUE TITLE
Empty attributes causes: Expected an identifer, line 1

### ISSUE THREAD

**Issue by MichaelRFairhurst** [dart-lang/angular_analyzer_plugin#108]
```
<my-comp [myInput]=""
```

Causes an error "expected an identifer" with no locational information.

@matanlurey Is this actually valid syntax?

If so, we need to accept it and/or typecheck it (how? Is this equivalent to 'null', or empty string, or something else?).

If not, we need to report the location correctly.

**Comment by zoechi** [comment]
I hope it's considered invalid.

**Comment by MichaelRFairhurst** [comment]
At best it should evaluate to 'null', in which case we should probably just prefer the user types in 'null' (not hard to type in!)

That said, this should probably be valid for event handlers:

```
   (click)=""
```

though I don't know why you would do that and not just delete the click handler...

**Comment by zoechi** [comment]
I don't see what purpose `(click)=""` or `(click)="null"` would provide. Ok, actually I used `(click)=""` a few times in Plunkers to get change detection invoked in very simple examples without any code.

I think usually it's just that dev was looking up what method name to put into and got distracted ;-)
I think it should be an error. Being too smart here will probably cause more confusion and hide bugs.

**Comment by MichaelRFairhurst** [comment]
Also, I should take the time now to note that I saw somewhere that `[input]=""` (and `[input]`? my memory is fuzzy) should be treated as `[input]="''"`

**Comment by zoechi** [comment]
I really would prefer a proper error message than some magic with questionable results. I don't think `[prop]="''"` or `(event)="''"`) is a common use case.

**Comment by MichaelRFairhurst** [comment]
Merged #159 which includes fixes for this
