### ISSUE TITLE
Autocomplete two-way bindings

### ISSUE THREAD

**Issue by MichaelRFairhurst** [dart-lang/angular_analyzer_plugin#139]
When you go to autocomplete a two way binding:

```
<input [(|
<input [(ngM|
<input [(|)]="blah"
< input [(ngM|)]="blah"
```

then it should provide a list of all inputs `n` where `nChanged` is an existing output, for autocomplete suggestions.

If it merely completes inputs that's better than nothing, but still.

**Comment by mk13** [comment]
PR #357
