### ISSUE TITLE
Gracefully abort analysis on pipes

### ISSUE THREAD

**Issue by MichaelRFairhurst** [dart-lang/angular_analyzer_plugin#155]
We can't typecheck pipes. Make sure we bail out of the analysis at the first '|' and make the expression 'dynamic' from there.

**Comment by MichaelRFairhurst** [comment]
Ideally this gets done by wednesday

**Comment by mk13** [comment]
Pull request 160.

**Comment by zoechi** [comment]
Why can't you typecheck pipes?

**Comment by MichaelRFairhurst** [comment]
We're just trying to get more useful features in first, like
autocompletion, but also don't want to leave the errors we get right now
where its treated as binary or. Max's solution is also like basically a
step in supporting them so we'll get to them eventually.

**Comment by zoechi** [comment]
I see. I got the impression that it's not possible in general. Thanks for the unfo.

**Comment by MichaelRFairhurst** [comment]
Absolutely! We are glad to be held accountable -- at the very least at
times like these it means the public information gives the wrong
impression, which is always a big deal for us that we'd want to fix. And if
we had decided not to or that we couldn't do it, we definitely would have
benefitted from a double-check on why.

On Sun, Dec 18, 2016 at 12:57 PM, Günter Zöchbauer <notifications@github.com
