### ISSUE TITLE
is it possible to use this project?

### ISSUE THREAD

**Issue by kasperpeulen** [dart-lang/angular_analyzer_plugin#17]
Would love to test this out :) Is that already possible?

**Comment by scheglov** [comment]
Sorry for the delay.
I forgot to watch the project.

It is still work in progress.
Resolution is mostly implemented, at least for the most useful cases.
So, we report resolution errors, have navigation and mark occurrences.
No semantic highlighting yet, no indexing and search, no completion.
But I'd love to implement all of this in the future :)

The Angular2 people are going (or have landed already) to make some additional changes from `ke-bab` to `camelCaseNames`, I will need to make more changes soon.

I test these two plugins by building a custom AnalysisServer starter, see https://github.com/angular/angular2-dart-analyzer/blob/master/server_plugin/bin/server.dart

**Comment by MichaelRFairhurst** [comment]
There are instructions now in the readme. Do please note it is still in pre-release, and you may find various issues.
