### ISSUE TITLE
ERROR: The argument type 'List<File>' can't be assigned to the parameter type 'FileList'. 

### ISSUE THREAD

**Issue by zoechi** [dart-lang/angular_analyzer_plugin#170]
```html
<input *ngIf="!readonly" #fileInput type="file" (change)="updateFiles(fileInput.files)">
```
I come up with the type `FileList` by checking at rntime what was passed to 

```dart
void updateFiles(FileList files) {
```
Not sure what is actuallly correct.

**Comment by MichaelRFairhurst** [comment]
This looks to me like one of those cases where a static error but not a runtime error is in your angular code, everything works but the analyzer.

FileList is a subtype of List<File>, but not the reverse. So this is correct, likely `updateFiles` only uses `files` as a `List<File>` and changing to that type would solve the error and catch the mistake of calling, for instance, `replaceRange` on `files` which will result in a method-not-found in this case.
