### ISSUE TITLE
WARNING: The bound input ngForTrackBy does not exist on any directives or on the element

### ISSUE THREAD

**Issue by zoechi** [dart-lang/angular_analyzer_plugin#173]
```html
<div class="flex-row"
         *ngFor="let item of items let i=index trackBy:trackByIndex">
```

**Comment by MichaelRFairhurst** [comment]
Once again, can you let me know if adding CORE_DIRECTIVES solves this?

**Comment by zoechi** [comment]
I forgot about platform_directives not being supported. I'm not sure if there was also an error for `ngFor` that I missed. I added the missing directives directly to the components. Now I don't get this one anymore.
