### ISSUE TITLE
WARNING: The bound input totalItems does not exist on any directives or on the element 

### ISSUE THREAD

**Issue by zoechi** [dart-lang/angular_analyzer_plugin#174]
I got an error for this unknown `<bs-pager>` component (removed from project).
When I commented out this line I got the error message in the title

```html
<!-- TODO <bs-pager [totalItems]="searchResult.total" [currentPage]="currentPage + 1" (currentPageChange)="pageChanged($event)"></bs-pager> -->
```

**Comment by MichaelRFairhurst** [comment]
Interesting. I'm wondering if the plugin crashed when the comment was opened but not closed.

Haven't reproed this yet but its definitely suspect

**Comment by zoechi** [comment]
I fixed or worked around a lot of reported issues and this error seemed to have vanished eventually, but while I had it killing the analyzer didn't help.

**Comment by MichaelRFairhurst** [comment]
I'm also going to close this one. I don't know if we can figure out what happened, hopefully the fuzz tester from #162 reveals any issues if it can still occur.
