### ISSUE TITLE
How to know how to suppress a warning/error

### ISSUE THREAD

**Issue by zoechi** [dart-lang/angular_analyzer_plugin#200]
I get
```
ERROR: The operands of the '||' operator must be assignable to 'bool'
```

```html
[disabled]="selectedItem.data.isDirectory"
```
because the return type of `selectedItem.data` is `dynamic`

Now I want to suppress that warning but how do I get the name to put into the comment (instead of `UNRESOLVED_TAG`

```html
<!-- @ngIgnoreErrors: UNRESOLVED_TAG -->
```

I think the warning should contain the id of the error/warning like

```
ERROR UNRESOLVED_TAG: The operands of the '||' operator must be assignable to 'bool'
```
or
```
ERROR: The operands of the '||' operator must be assignable to 'bool' (UNRESOLVED_TAG)
```

**Comment by zoechi** [comment]
Just found that in IntelliJ I get a quick fix suggestion "Suppress error with comment" which changes

```html
<material-button card-action
                   [disabled]="selectedItem.data.isDirectory">Load</material-button>
```
into 
```html
<material-button card-action
                   // ignore: non_bool_operand
                   [disabled]="selectedItem.data.isDirectory">Load</material-button>
```

Perhaps if this would add the correct comment the original issue could be considered as fixed, while it still would require an IDE with quick-fix support to figure out how to suppress the error/warning but it would cover 99% (IMHO) of the use cases.

**Comment by zoechi** [comment]
Should 

```html
<!-- @ngIgnoreErrors: non_bool_operand -->
<material-button card-action
                   [disabled]="selectedItem.data.isDirectory">Load</material-button>
``` 
actually suppress the warning? 
For me it doesn't.

**Comment by MichaelRFairhurst** [comment]
Its still pretty experimental so I'm not sure if we'll be publishing an official list.

I think the error code you want to ignore is "INPUT_BINDING_TYPE_ERROR". But I'm not sure what's up with the `The operands of the '||' operator must be assignable to 'bool'` because your example doesn't include the operator `||`.

**Comment by zoechi** [comment]
I'm going to close this. 
The code and the error message don't match. Sorry for that.
