### ISSUE TITLE
Standard attributes not accepted on custom components

### ISSUE THREAD

**Issue by zoechi** [dart-lang/angular_analyzer_plugin#201]
```html
<material-progress progress-bar [hidden]="!isIndeterminateAction"
```
causes
```
WARNING: The bound input hidden does not exist on any directives or on the element
```
https://developer.mozilla.org/en/docs/Web/HTML/Global_attributes/hidden

**Comment by zoechi** [comment]
Not sure what you mean with HTML5 compliant here and "Global attributes may be specified on all HTML elements". `[hidden]="..."` is never added to the DOM. 
`[...]="..."` is **property** binding (not attribute binding) and just processed by Angular and translated to JS code.

**Comment by MichaelRFairhurst** [comment]
I just mean that angular didn't have to support global properties on
components. But they did :)

**Comment by MichaelRFairhurst** [comment]
Merge #215
