### ISSUE TITLE
Need more documentation on how to use with Angular dart 2.0

### ISSUE THREAD

**Issue by sureshg** [dart-lang/angular_analyzer_plugin#22]
Is there any doc available on how to use `angular2-dart-analyzer` with angular dart 2.0 projects in Webstrom?

**Comment by zoechi** [comment]
It's not even released to pub. Give them some time to complete development before they write docs ;-)

**Comment by sureshg** [comment]
@zoechi np..i completely understand that 😄

**Comment by MichaelRFairhurst** [comment]
There are installation instructions now on the main page. Feel free to give it a try, but do remember it is still a pre-release form.
