### ISSUE TITLE
Supply proper completionLength, completionOffset

### ISSUE THREAD

**Issue by MichaelRFairhurst** [dart-lang/angular_analyzer_plugin#223]
Looks like IntelliJ will start using these offsets to let us deal with the complex problem of knowing what to replace. Just in general, we should assume that all editors use this info (though IntelliJ used to ignore it and I think vim ignores it too).

**Comment by zoechi** [comment]
Is this related or should I create a new issue? (missing ` != null`)

![image](https://cloud.githubusercontent.com/assets/405837/22248543/53d3c018-e23f-11e6-8877-b89f0593b9b8.png)

**Comment by MichaelRFairhurst** [comment]
this only has to do with autocompletion

**Comment by zoechi** [comment]
Sorry, didn't read properly. I removed the comment and created #241

**Comment by MichaelRFairhurst** [comment]
this is done...merged in PR... #226
