### ISSUE TITLE
HTML comments cause error "unexpected-char-in-comment"

### ISSUE THREAD

**Issue by zoechi** [dart-lang/angular_analyzer_plugin#231]
![image](https://cloud.githubusercontent.com/assets/405837/22056441/6f2c429c-dd60-11e6-918f-3c9324d0ff0c.png)

**Comment by MichaelRFairhurst** [comment]
This actually is a parse error. Its just a harmless one.

We can suppress it.

**Comment by MichaelRFairhurst** [comment]
Also closing this since it should be solved with angular_ast very soon
