### ISSUE TITLE
Unresolved tag "material-input"

### ISSUE THREAD

**Issue by rxlabz** [dart-lang/angular_analyzer_plugin#245]
I use some material inputs from [Angular2_components](https://github.com/dart-lang/angular2_components) in my templates , and have warnings : *Unresolved tag "material-input"*

Maybe it's caused by its declaration ?

```dart
@Component(
    selector: 'material-input:not(material-input[multiline])',
)
```

**Comment by zoechi** [comment]
Looks like a dup of #171

**Comment by rxlabz** [comment]
Yes, and I should have update first... no more warnings with current version!
