### ISSUE TITLE
Travis failing on dev branch

### ISSUE THREAD

**Issue by kevmoo** [dart-lang/angular_analyzer_plugin#246]
https://travis-ci.org/dart-lang/angular_analyzer_plugin/jobs/198177025

This seems bad – let's make sure we don't have breaking changes or regressions we're not aware of.

**Comment by MichaelRFairhurst** [comment]
We haven't been developing off of the latest SDK since it doesn't work, but that's what travis is doing because in the long run that's what matters.

Once the new plugin arch is done, this will be green again.
