### ISSUE TITLE
`disabled` property on `<select>` not recognized

### ISSUE THREAD

**Issue by zoechi** [dart-lang/angular_analyzer_plugin#256]
```html
<select [(ngModel)]="language"
        (ngModelChange)="update()"
        [disabled]="readonly" class="form-control">
````

> WARNING: The bound input disabled does not exist on any directives or on the element ([myproj] lib/src/webui_generated/valueset_lookup/language_lookup_component.html:10)

**Comment by MichaelRFairhurst** [comment]
Also the latest?

**Comment by zoechi** [comment]
Yes, latest. I updated today and I still get this one.

**Comment by MichaelRFairhurst** [comment]
Managed to repro, fix. Opened #262

**Comment by MichaelRFairhurst** [comment]
#262 merged
