### ISSUE TITLE
`src` property not recognized on `<img>`

### ISSUE THREAD

**Issue by zoechi** [dart-lang/angular_analyzer_plugin#257]
```html
<img [src]="imageUrl">
```
> WARNING: The bound input src does not exist on any directives or on the element ([myproj] lib/webui/oauth2/google_login_button_component.html:1)

**Comment by zoechi** [comment]
I forgot to mention that it also complains about the `alt` property.

**Comment by MichaelRFairhurst** [comment]
Duplicate of #256
