### ISSUE TITLE
directives from arrays not recognized

### ISSUE THREAD

**Issue by zoechi** [dart-lang/angular_analyzer_plugin#258]
```dart
@Component(
  selector: 'dropdown-menu',
  directives: const <dynamic>[
    materialInputDirectives,
  ],
```
> WARNING: A type literal expected ([myproj] lib/webui/dropdown_menu/dropdown_menu_component.dart:25)

```html
<material-input></material-input>
```
> WARNING: Unresolved tag "material-input" ([myproj] lib/webui/dropdown_menu/dropdown_menu_component.html:5)

**Comment by MichaelRFairhurst** [comment]
This is with the latest?

Usually this means that one of the items in the directives list had an analysis error low level (like in the selector). But I also thuoght I had given that a better error in the latest

**Comment by zoechi** [comment]
It is with 
> Dart VM version: 1.23.0-edge.1c4710469541ab27644b07535618e69605d4b548 (Tue Mar 28 23:55:26 2017) on "linux_x64"
and I updated the plugin just now.
The application runs fine and I have this for all array references (`ROUTER_DIRECTIVES, materialInputDirectives, some of my own)
I don't get the "type literal expected" warning without the plugin.

```yml
analyzer:
  strong-mode:
    implicit-casts: false
    implicit-dynamic: false

# and most linter rules enabled
```

**Comment by MichaelRFairhurst** [comment]
Open https://github.com/dart-lang/angular_analyzer_plugin/pull/260

**Comment by MichaelRFairhurst** [comment]
#260  merged. Should be fixed!
