### ISSUE TITLE
template element should be ignore for transclusion checking

### ISSUE THREAD

**Issue by zoechi** [dart-lang/angular_analyzer_plugin#294]
![image](https://cloud.githubusercontent.com/assets/405837/25434087/3c9ce78c-2a8b-11e7-8b26-512b4ebd579d.png)

at least if there is no `@ViewChild(TemplateRef)` or as constructor parameter (actually not sure if injecting a transcluded template using the constructor works, I think it did at one point, at least in TS)

**Comment by zoechi** [comment]
Might be covered by https://github.com/dart-lang/angular_analyzer_plugin/pull/291

> Validates:
>  ...
>  - TemplateRef

**Comment by MichaelRFairhurst** [comment]
Yes, this will be handled by that branch!

**Comment by MichaelRFairhurst** [comment]
Going to close this, as that branch was merged. Please reopen if it isn't gone!
