### ISSUE TITLE
`@ContentChildren` ignores `read` parameter and therefore complains about valid type

### ISSUE THREAD

**Issue by zoechi** [dart-lang/angular_analyzer_plugin#320]
![image](https://cloud.githubusercontent.com/assets/405837/26026830/29627ae4-3803-11e7-8d09-4e8c72046789.png)

Probably similar with `@ContentChild()`, `@ViewChildren()`, `@ViewChild()`

**Comment by MichaelRFairhurst** [comment]
Hmm, I will have to look into how this parameter works...Thanks!
