### ISSUE TITLE
Suggest inputs/outputs for unmatched directives

### ISSUE THREAD

**Issue by MichaelRFairhurst** [dart-lang/angular_analyzer_plugin#333]
If I have a directive like

```
@Directive(selector: '[foo]', inputs: ['foo'])
class Foo { ... }
```

I will never get recommended `[foo]`. Why? Because we only recommend inputs for matched directives. `Foo` isn't matched until we have `[foo]`, and once we have `[foo]` we won't suggest it again.

Most relevant example: `NgModel`. (kinda a big deal)

Of course, `Foo` may have another input, and an output, which don't correlate with the selector. These won't be suggested until '[foo]' has been bound, which may not match the most readable API. For instance, perhaps `<div (trigger)="bar" [onUniversal]="click">` where `[onUniversal]` matches some directive with output `trigger`. Not sure how common this is.

We could do one or both of
* suggest all directive inputs regardless of whether they've been matched yet, at a very low priority
* suggest self-fulfilling inputs like these, of unmatched directives, at a lowered priority

note that we shouldn't need to handle this problem for Components, because the vast majority of components are matched correctly at the correct time since they use tag names. Of course, this is not guaranteed, either.

I say we start with the second approach, for directives only, and wait for feedback that inputs are missing.

**Comment by mk13** [comment]
Done.
