### ISSUE TITLE
Make new plugin arch publishable for easier beta use

### ISSUE THREAD

**Issue by MichaelRFairhurst** [dart-lang/angular_analyzer_plugin#344]
Issues preventing publishing:

- [ ] autocompletion support
- [ ] more testing & bugfixes (probably)
- [ ] angular_ast dependent version not published, not in pubspec @mk13
- [ ] analyzer_plugin package not published @bwilkerson 
- [ ] poor naming (`angular_analysis_plugin` vs `angular_analyzer_plugin`!) @MichaelRFairhurst
- [ ] dependency on `analysis_server` for `starter` in `angular_analyzer_plugin`, should be its own package (which doesn't need to be published) @MichaelRFairhurst
- [ ] dependency on `analysis_server` for completions @bwilkerson 
- [ ] formalization and publication of the empty analyze_angular package which turns on analysis, but requires `import 'package:analyze_angular/analyze_angular.dart` for no reason. Should we make `-analyzed` angular release versions, ie `3.0.1-beta-analyzed` which just add [these files](https://github.com/dart-lang/angular_analyzer_plugin/tree/master/analyze_angular/tools/analysis_plugin)?

**Comment by bwilkerson** [comment]
> poor naming ...

Also, it's convention to give the directory that contains a package the same name as the package, which isn't currently the case (and would have caught this conflict).

> formalization and publication of the empty analyze_angular package ...

My expectation is that that package will go away at the point at which you're ready to ship the plugin. The embedded plugin within that package should be moved into the angular2 package.

That does leave the interesting question of how to beta test the plugin if you want to release it to a limited initial audience.

**Comment by MichaelRFairhurst** [comment]
> My expectation is that that package will go away at the point at which you're ready to ship the plugin....That does leave the interesting question of how to beta test the plugin if you want to release it to a limited initial audience.

I was thinking the `analyzed_angular` package handle that beta release. Installations steps would be "add analyzed_angular to your pubspec and import it in main.dart. Done!" But the right package name, and coordinating with the angular team, would be important.

Alternatively special beta angular releases wouldn't require a special package, and would also be 'opt-in'. But we'd have to coordinate with the angular team and see if that fits with their current intended semantic versioning stuff.

>  it's convention to give the directory that contains a package the same name as the package, which isn't currently the case (and would have caught this conflict)

We don't actually have a conflict, but I'd agree that our directories are part of our naming problem. I for instance, named the new plugin `new_plugin` instead of `analysis_plugin` or `angular_analysis_plugin` (the package name) because I knew having two folders `*analysis_plugin` and `analyzer_plugin` would be confusing. Fixing that confusion requires renaming the `angular_analysis_plugin` package, which I'm reluctant to do just this moment, for backwards compatibility reasons.

I'm thinking very soon we can move to something like:

- angular_analysis_plugin_old_loader (analysis_plugin/lib/starter.dart)
- angular_analysis_core (server_plugin + analyzer_plugin)
- angular_analysis_plugin (new_plugin)
- angular_analysis_plugin_beta_loader (analyze_angular)

Maybe we don't need a separate `core` and `angular_analysis_plugin`. And we won't need to publish `old_loader`. 

And `angular_analysis_plugin_beta_loader` could be part of angular special builds....and...hmm....would it be possible to include `tools/analysis_plugin` inside `angular_analysis_plugin`? It would, wouldn't it? At least temporarily?

That would leave us with:

- angular_analysis_plugin_old_loader (never to be published)
- angular_analysis_plugin (server_plugin + analyzer_plugin + new_plugin + analyze_angular)

and the install steps would be "add angular_analysis_plugin to your pubspec and import package:angular_analysis_plugin/noop.dart in your main.dart file. Done!"

**Comment by bwilkerson** [comment]
> ... would it be possible to include `tools/analysis_plugin` inside `angular_analysis_plugin`?

As long as some library in `angular_analysis_plugin` is imported into the package being analyzed, yes. But it's a little odd (and a bit mind-bending) for a package *P* to trigger the loading of a plugin based on *P*.

**Comment by mk13** [comment]
I'll look into adding pub support for angular_ast once pipes are added - that might be the last major ast addition that will be needed.

**Comment by MichaelRFairhurst** [comment]
I think the crazy solution of having package P load itself is the best -- until the angular team is ok giving us some kind of beta releases (either put us in the main beta releases, or offshoots). Hopefully once we're ready to publish they can give us that sooner rather than later so that we don't have to have a day of anything so crazy -- but if we do, it won't involve publishing a package for a single days' beta use.

**Comment by MichaelRFairhurst** [comment]
I'll also check if having P include a plugin that loads P, test if that creates any issues when P imports its own files lol

**Comment by MichaelRFairhurst** [comment]
This is very old, and currently implemented. Closing!
