### ISSUE TITLE
Should (click) etc be available on <template>s? How about [content]?

### ISSUE THREAD

**Issue by MichaelRFairhurst** [dart-lang/angular_analyzer_plugin#373]
`content` is a member of `TemplateElement`. Should it be bindable? All the other suggetions are members of `HtmlElement`. Should they be bindable?

Currently they are.

If `(click)` should not be bindable, we need to do some special logic there to suppress that (since its available everywhere).

If `[content]` is not bindable, then we should not make `TemplateElement` into a `Component` at all, internally, most likely.

**Comment by zoechi** [comment]
`<template>` and it's content isn't rendered. It's just a container of markup that can be stamped to the DOM one or more time. Event binding doesn't make sense.
https://developer.mozilla.org/en/docs/Web/HTML/Element/template

What is `[content]` here?

**Comment by MichaelRFairhurst** [comment]
That's what I had figured:

Content shown here https://developer.mozilla.org/en-US/docs/Web/API/HTMLTemplateElement

**Comment by zoechi** [comment]
`content` seems to be just a getter.

**Comment by MichaelRFairhurst** [comment]
Ah, that it is. Looks like we don't suggest/accept `[content]`. Should have checked.

**Comment by MichaelRFairhurst** [comment]
The answer here is "no and no"
