### ISSUE TITLE
Question about the direction of this project

### ISSUE THREAD

**Issue by daniel-v** [dart-lang/angular_analyzer_plugin#445]
This is more of a "manage expectation" query for those who work on the plugin.

As of opening this issue (16/October) , the last issue was closed over a month ago (15/Sept). There were no new commits for over a month either.

What I'd like to know is: can I hope this project to keep on developing or is the current state what we get?

**Comment by MichaelRFairhurst** [comment]
Sorry Daniel,

I haven't been working on the open source side of things as much, and this project is not longer all of my time.

However, it is very much used internally and its definitely still being supported whenever I get the chance.

The external story here is lower priority than working on Dart 2, but its in motion, so we can do official announcement/launch/etc after we make any last minute changes we need to before then! :)

That said, one reason for its slow movement from here is that it seems to be working really, really well internally. So "current state" _should be_ very useful. Are you still having issues loading it? And you're on windows, right?

**Comment by MichaelRFairhurst** [comment]
Just closed about 11 issues or so which we had fixed but not taken care of in the bugtracker here.

Looks like you were on one of them (#289), so, I really apologize for not updating that which you would have gotten a notification for.

I will look into publishing a new version, I can think of some reasons why it might not work, but if I can publish successfully, and you are loading the plugin via

```
analyzer:
  plugins:
    angular_analyzer_plugin:
     enabled: true
```

then you should be able to pub update to the new version.

Huge apologies. It's really to nobody's benefit that the last published version has a bug solved long ago that blocks you from using it when it has so many (I think, at least) useful features.

**Comment by daniel-v** [comment]
@MichaelRFairhurst I value such open communication and appreciate your capacity to write such responses. 

As soon as you find the time to release a new version, I'll give it another go.

> Are you still having issues loading it?

I gave up after some debugging and lots of failing. I'd say yes, since little has changed in the SW stack since. (beaware: this is an assumption)

> And you're on windows, right?

Yes.

**Comment by MichaelRFairhurst** [comment]
Quick update: the publish we just merged didn't work, something our tests missed. That what #462 is for, but will cause a bit of a delay.

**Comment by MichaelRFairhurst** [comment]
OK, 0.0.11+1 is out and works!

The way I used it was to `rm -r ~/.dartServer/.plugin-manager/*`, and then restarting my analysis server.

On windows, it may be safer to try running `pub upgrade angular_analyzer_plugin` from within `~/.dartServer/.plugin-manager/**hash**`.

You can also try adding `angular_analyzer_plugin` to your pubspec, and putting

```
analyzer:
  plugins:
    angular_analyzer_plugin:
      enabled: true
```

in your `analysis_options.yaml` file. That way you can specify exactly which version of the angular plugin you want.

Let me know if that works or if you have any issues!

**Comment by daniel-v** [comment]
@MichaelRFairhurst I believe this  issue has served it's purpose and is starting the become kind of a personal support ticket. I think it's safe to close; you did answer the questions I originally opened this issue for.

I'll open issues should I encounter any problems. Thanks!
