### ISSUE TITLE
Analyzer doesn't understand FutureOr

### ISSUE THREAD

**Issue by Bobby-Seidensticker** [dart-lang/angular_analyzer_plugin#450]
FutureOr<T> accepts a Future<T> or a T.  In a template I pass a T to an input that takes a FutureOr<T> and I get this warning:

warning: Attribute value expression (of type List<Line>) is not assignable to component input (of type FutureOr<List<Line>>) (input_binding_type_error at [explore_target_spend_chart] demo/lib/explore_target_spend_chart_demo.dart:64)

**Comment by MichaelRFairhurst** [comment]
Thanks for filing!

This definitely shouldn't happen, I'll look into why its not accepting it!

**Comment by MichaelRFairhurst** [comment]
Should be fixed!
