### ISSUE TITLE
Improve error message for * on <template> element

### ISSUE THREAD

**Issue by leonsenft** [dart-lang/angular_analyzer_plugin#451]
Currently using the `*` sytnax on a `<template>` element like

```html
<template *ngIf="condition">
```

produces the error message

> Invalid decorator in 'template' element

Providing a link to the[ `*` documentation](https://webdev.dartlang.org/angular/guide/structural-directives#the-asterisk--prefix) could be more helpful for new users.

**Comment by MichaelRFairhurst** [comment]
Going to close this in favor of the angular_ast ticket
