### ISSUE TITLE
*ngIf attribute shown as invalid on <ng-content>

### ISSUE THREAD

**Issue by tetkin-g** [dart-lang/angular_analyzer_plugin#464]
Example template:
```
<ng-content select="[foo]" *ngIf="showFoo"></ng-content>
```

The analyzer shows "Only 'select' is a valid attribute/decorate in `<ng-content>`".

**Comment by zoechi** [comment]
`<ng-content>` is not an element that is added to the DOM, it is only handled internally in Angular code.
`*ngIf` is about adding/removing elements to/from the DOM, therefore this can't work. 

This might work

```html
<div *ngIf="showFoo">
  <ng-content select="[foo]"></ng-content>
</div>
```

**Comment by tetkin-g** [comment]
Wouldn't it be equivalent to this?

```
<template [ngIf]="showFoo">
   <ng-content select="[foo]"></ng-content>
</template>
```

**Comment by zoechi** [comment]
Right, didn't think of `<template>`

**Comment by MichaelRFairhurst** [comment]
This will not work for long inside angular; the decision is that `<ng-content>` is a grammatical construct and it's not necessarily a good idea to support every combination of every grammatical construct. We report the error because we use the next gen parser; but angular will be using that parser probably early next year too.

**Comment by tetkin-g** [comment]
Is there a preferred way to have an conditionally shown `<ng-content>` that doesn't involve wrapping it in an element in the resulting DOM structure?

**Comment by MichaelRFairhurst** [comment]
Currently, no, not that I know of. Unless the `<template>` approach works? I know a lot less about angular's runtime than what I can determine statically :)

@matanlurey @alorenzen wondering your suggestion here.

**Comment by MichaelRFairhurst** [comment]
Closing this, now angular supports `<ng-container>`.
