### ISSUE TITLE
Analyzer doesn't work in example project on Windows

### ISSUE THREAD

**Issue by Thiltal** [dart-lang/angular_analyzer_plugin#489]
Example project repository:

https://github.com/Thiltal/angular_analyzer_plugin_example

Platform: Windows

Screenshots are included in root of repository.

**Comment by MichaelRFairhurst** [comment]
Hi @Thiltal so sorry for not seeing this earlier!!

I am going to try to get my hands on a windows machine to repro.

Huge thanks for making a repo!! That will be *enormously* helpful!!

**Comment by MichaelRFairhurst** [comment]
OK,  I got a windows laptop about a week ago and got some time to get everything set up and dig in!

With the issues that I've been seeing, the easiest way to debug is to click on the settings bar of the analysis panel (in IntelliJ at least) and then go to open analyzer diagnostics. In the menu, there's an option for "plugins."

At first I saw an issue with "The system does not recognize ..." which seems to be related to the space in "Program Files"... do you also have your sdk in a directory with a space? Can you check you're getting the same error?

After that, I was able to `cd` into `C:/Users/mfairhurst/AppData/Local/.dartServer/.plugin_manager` and I had a hash directory `14188e4bb62a73fae7b88c1fa0a5ebe9`. Yours may be different, and you may have multiple. At any point it should be safe to delete these, that will just trigger a reinstall on analyzer reboot.

Going into `14188e4bb62a73fae7b88c1fa0a5ebe9/analyzer_plugin` and running `pub get`, it then almost worked for me, except I got

```
Failed to rename directory because access was denied.
This may be caused by a virus scanner or having a file
in the directory open in another application.
```

Rebooting the analyzer, and opening up the new diagnostics page, the plugins section shows:

```
Could not create "C:\Users\mfairhurst\AppData\Local\.dartServer\.plugin_manager\14188e4bb62a73fae7b88c1fa0a5ebe9\analyzer_plugin\.packages".
```

You may or may not hit the same issue. I'm working on this right now.

Could you try the steps I showed above related to spaces in the directory? If so, we should be able to patch the SDK to escape it in this case.

On to the next issue I hit!

**Comment by MichaelRFairhurst** [comment]
OK, the antivirus related issue magically went away (drat). Can't reproduce it again...

The other issue is that I haven't clearly specified in the README (oops) is that its currently only working reliably in angular 5 alphas.

However, there is a workaround for you that may be useful: if you pull in `angular_analyzer_plugin: ^0.0.13` as a dev_dependency, and then specify `plugins: angular_analyzer_plugin: enabled: true` (formatted better than that though!) then you get to pull in a newer version than what angular 4 offers, which works better. I can test this workflow later on.

I'll get started on a test & fix for the "Program Files" issue and hopefully one of the next few bleeding edge SDKs will have the fix!

**Comment by MichaelRFairhurst** [comment]
OK! Doesn't seem to be an issue with the space, but rather, it needs ".bat" to run inside "process.runSync" correctly. Otherwise, all info  here is still the same.

**Comment by Thiltal** [comment]
Thanks for your investigations. I will update example project to Ng5 and will check analyzer diagnostics.

**Comment by Thiltal** [comment]
One bug report when run pub get on example repository:

Analyzer Feedback from IntelliJ

# Version information

- `IDEA WS-173.4548.30`
- `1.25.0-dev.16.4`
- `WS-173.4548.30, JRE 1.8.0_152-release-1024-b11x64 JetBrains s.r.o, OS Windows 10(amd64) v10.0 , screens 1920x1080`

# Exception

Please append the contents of:
file://C:\Users\Tal\AppData\Local\Temp\report.txt

```
Dart analysis server, SDK version 1.25.0-dev.16.4, server version 1.18.4, FATAL error: Failed to handle request: {id: 3, method: analysis.setAnalysisRoots, params: {included: [C:\project\angular_analyzer_plugin_example], excluded: [C:\project\angular_analyzer_plugin_example\.idea, C:\project\angular_analyzer_plugin_example\.pub, C:\project\angular_analyzer_plugin_example\.tmp, C:\project\angular_analyzer_plugin_example\build, C:\project\angular_analyzer_plugin_example\temp, C:\project\angular_analyzer_plugin_example\tmp]}, clientRequestTime: 1519766835491}
NoSuchMethodError: The getter 'analysisOptions' was called on null.
Receiver: null
Tried calling: analysisOptions
#0      Object._noSuchMethod (dart:core-patch/object_patch.dart:42)
#1      Object.noSuchMethod (dart:core-patch/object_patch.dart:46)
#2      ContextManagerImpl._updateContextPackageUriResolver (package:analysis_server/src/context_manager.dart:1569)
#3      ContextManagerImpl._recomputeFolderDisposition (package:analysis_server/src/context_manager.dart:1525)
#4      ContextManagerImpl._handleWatchEvent (package:analysis_server/src/context_manager.dart:1308)
#5      _rootRunUnary (dart:async/zone.dart:1128)
#6      _CustomZone.runUnary (dart:async/zone.dart:1012)
#7      _CustomZone.runUnaryGuarded (dart:async/zone.dart:909)
#8      _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:330)
#9      _BufferingStreamSubscription._add (dart:async/stream_impl.dart:257)

**Comment by Thiltal** [comment]
I've tried to upgrade, but ends with version of Dart SDK. "Requires angular-5.0.0* and dart SDK 2.0.0-dev.31** or higher to work." -> [https://www.dartlang.org/install/archive](https://www.dartlang.org/install/archive)

Requested version of SDK (2.0.0-dev.31**) is higher than last version available on download page.

**Comment by Thiltal** [comment]
Upgraded example repository to 
environment:
  sdk: '2.0.0-dev.31.0'

dependencies:
  angular: 5.0.0-alpha+6

Still not working. I will wait for fixes

**Comment by rasdev** [comment]
In the plugin directory I get an exception when I call "dart plugin.dart".

Environment: 2.0.0-dev.32.0 (Thu Mar 1 18:39:53 2018 +0100) on "windows_x64"

`
\.dartServer\.plugin_manager\96a1a0002b11dcd84700c49af19363c8\analyzer_plugin>dart bin\plugin.dart
Unhandled exception:
NoSuchMethodError: The method 'send' was called on null.
Receiver: null
Tried calling: send(SendPort)
#0      Object.noSuchMethod (dart:core-patch/dart:core/object_patch.dart:46)
#1      new PluginIsolateChannel (package:analyzer_plugin/src/channel/isolate_channel.dart:108:15)
#2      Driver.start (package:analyzer_plugin/src/driver.dart:30:40)
#3      start (package:angular_analyzer_plugin/starter.dart:14:8)
#4      main (file:///C:/Users/Gateway/AppData/Local/.dartServer/.plugin_manager/96a1a0002b11dcd84700c49af19363c8/analyzer_plugin/bin/plugin.dart:7:3)
#5      _startIsolate.<anonymous closure> (dart:isolate-patch/dart:isolate/isolate_patch.dart:275)
#6      _RawReceivePortImpl._handleMessage (dart:isolate-patch/dart:isolate/isolate_patch.dart:165)
`

**Comment by MichaelRFairhurst** [comment]
This should now be fixed!

So sorry for everyone who got hit by this!
