### ISSUE TITLE
Find erroroneous usage of "let" vs "#"

### ISSUE THREAD

**Issue by MichaelRFairhurst** [dart-lang/angular_analyzer_plugin#53]
`let` can _only_ be used in templates, and `#` can _only_ be used in non templates.

This is actually pretty arbitrary and confusing, even if its less confusing than having `#` do everything from ngFor to `#form="ngForm"`.

Still, this is probably a great place to have a tool help people use the right ones especially when they are new.

**Comment by mk13** [comment]
Considering use cases for writing tests: 

<div *ngFor="let hero of heroes | async"
         (click)="gotoDetail(hero)" class="search-result" #currentHero >
      {{currentHero.name}}
</div>

'#currentHero' should be highlighted to indicate that '#' should not be used within a template.

**Comment by mk13** [comment]
Resolved with pull request 157.

**Comment by MichaelRFairhurst** [comment]
Maybe we should make a new ticket for disallowing let outside of templates?
