### ISSUE TITLE
Enabling the plugin with angular 5.0.0 results it strange analyzer warnings

### ISSUE THREAD

**Issue by johnpryan** [dart-lang/angular_analyzer_plugin#530]
I have a pubspec like this:

```
dependencies:
  angular: 5.0.0-alpha+8
  angular_components: 0.9.0-alpha+8


```

and i'm getting strange errors:

![screen shot 2018-03-27 at 12 11 41 pm](https://user-images.githubusercontent.com/1145719/37989388-29c7ca02-31b8-11e8-860e-228b820712a6.png)

![screen shot 2018-03-27 at 12 11 03 pm](https://user-images.githubusercontent.com/1145719/37989413-3d36ece4-31b8-11e8-9107-3120972079f8.png)

I think it has something to do with this plugin, when I disable the plugin the errors go away:

```
analyzer:
  strong-mode: true
#  plugins:
#    angular:
#      enabled: true
```

**Comment by zoechi** [comment]
Please check if deleting `~/.dartServer/.analysis-driver/` fixes it

**Comment by MichaelRFairhurst** [comment]
These are extremely strange errors, aren't they!

I'm wracking my brain for how changing the plugin settings could affect something like "dart:html can't have a port-of directive."

What version of dart are you running? And like @zoechi said, removing `~/.dartServer/.analysis-driver` is a great thing to check as well.

**Comment by johnpryan** [comment]
removing ~/.dartServer/.analysis-driver fixed it for me

**Comment by MichaelRFairhurst** [comment]
Great! Thanks for filing. We must have gotten an invalid cache somehow. I will see if we can find where that could have been introduced, and what we can do so that it doesn't become a quietly broken experience in detectable cases
