### ISSUE TITLE
Rename package to angular_analyzer (?)

### ISSUE THREAD

**Issue by matanlurey** [dart-lang/angular_analyzer_plugin#54]
(Or whatever makes more sense)

/cc @MichaelRFairhurst

**Comment by kevmoo** [comment]
Renamed the repo - https://github.com/dart-lang/angular_analyzer_plugin

Still need to rename the two packages here. Not sure who's going to run with that.

**Comment by MichaelRFairhurst** [comment]
For pubspec.yaml I'm thinking 'angular_analyzer_plugin' and 'angular_analyzer_server_plugin', does that look good? Currently they are 'angular2_analyzer_plugin' and 'angular2_server_plugin'.

Also, should I be changing the 'library' definitions in the source code? I don't understand well what the library declaration does. Currently it looks like "angular2.src.analysis.analyzer_plugin" and "angular2.src.analysis.server_plugin".

**Comment by kevmoo** [comment]
> For pubspec.yaml I'm thinking 'angular_analyzer_plugin' and 'angular_analyzer_server_plugin', does that look good? Currently they are 'angular2_analyzer_plugin' and 'angular2_server_plugin'.

Yup.

> Also, should I be changing the 'library' definitions in the source code? I don't understand well what the library declaration does. Currently it looks like "angular2.src.analysis.analyzer_plugin" and "angular2.src.analysis.server_plugin".

Unless there are parts, annotations, or comments on the library definition, you can delete them. Or update them. No huge urgency

**Comment by MichaelRFairhurst** [comment]
PR #66 merged
