### ISSUE TITLE
[Warning] Static members from supertypes must be qualified by the name of the defining type 

### ISSUE THREAD

**Issue by akaufmann** [dart-lang/angular_analyzer_plugin#567]
Angular >= 5.0.0-alpha+9 allows to define properties and methods of a component be referenced without a receiver in the component's own template but this is not working for me with the plugin.

```dart
class TestComponent {
  static final String title = 'Test';
}
```

![bildschirmfoto 2018-05-07 um 13 38 52](https://user-images.githubusercontent.com/288499/39700080-2956ae26-51fc-11e8-8860-2817f6236872.png)

This is just a warning, so I don't know if this is just by design.

```bash
Dart VM version: 2.0.0-dev.52.0 (Tue May 1 18:36:36 2018 +0200) on "macos_x64"
Analyzer v0.31.1
Angular Analyzer Plugin v0.0.15+1
Angular v5.0.0-alpha+11
```

**Comment by MichaelRFairhurst** [comment]
Ah yes!

Thanks for filing, I had been warned about this but neglected to make a ticket to track.
