### ISSUE TITLE
Eliminate uses of deprecated CONSTANTS

### ISSUE THREAD

**Issue by leafpetersen** [dart-lang/angular_analyzer_plugin#588]
This package uses the deprecated SCREAMING CAPS CONSTANTS which are about to be removed for Dart 2 (specifically UTF8).  This tool is available for the migration:  https://github.com/dart-lang/dart2_fix .

**Comment by leafpetersen** [comment]
cc @munificent

**Comment by devoncarew** [comment]
Looks like this was fixed in https://github.com/dart-lang/angular_analyzer_plugin/commit/a6c642a60df67d8c3bef5ea3bbc3f2cb3d72f1b5; we'll need to re-publish the package so users can see this change.
