### ISSUE TITLE
Updates inconsistent

### ISSUE THREAD

**Issue by cooler-king** [dart-lang/angular_analyzer_plugin#614]
While update behavior is improved from https://github.com/dart-lang/angular_analyzer_plugin/issues/538 it is still inconsistent for me.

Dart 2.0.0
WebStorm 2018.2
0.0.17+2
Windows 10 

Sometimes the hints show up, sometimes they don't.  Even restarting the analyzer will usually only get a small portion of the full load (if any).  Kicking the analyzer by opening a specific HTML file or making a change in an HTML file or a change in the scope filter will often wake it up and more hints will appear (but not necessarily all hints).

Changes in sister Dart files do not seem to reliably trigger angular analyzer updates either.

**Comment by MichaelRFairhurst** [comment]
It looks like its crashing, I think this is the same thing reported in #602.

Sorry, the dart 2 migration has not gone super smoothly for this plugin (I've been working on Dart 2 instead!)

Will report back on this ticket when #602 is resolved!

**Comment by cooler-king** [comment]
The OP closed 602 but I still see these issues
