### ISSUE TITLE
No error for tags that don't use hyphen

### ISSUE THREAD

**Issue by drbcode** [dart-lang/angular_analyzer_plugin#634]
```
<!-- no error -->
<ab>
</ab>
<!-- warning: Unresolved tag "a-b" -->
<a-b>
</a-b>
```

angular_analyzer_plugin version: 0.0.17+3
Dart VM version: 2.0.0

**Comment by MichaelRFairhurst** [comment]
Thanks for filing!

Yes, this is covered by #248 !

Every time I've tried to enable this, I find a new plain HTML tag that gets invalidly reported (ex: `<audio>` was one!).

I think it's a good time for me to take another swing at this though.
