### ISSUE TITLE
Camel case properties should be treated with dashes in template code

### ISSUE THREAD

**Issue by MichaelRFairhurst** [dart-lang/angular_analyzer_plugin#73]
Seeing this in an example project:

```@View(
    template: '''
      <!-- pass the result of an expression into GnomePics, #PassingDataToSubComponents -->
      <gnome-pics [is-sleeping]="isSleeping"></gnome-pics>
       ...
    ''',
    directives: const [GnomePics, NgIf]
    )
class GnomeConscious {
  bool isSleeping = false;
  ...```

Error is "the bound input does not exist on any directives" until you change it to `[isSleeping]` in the template.

**Comment by MichaelRFairhurst** [comment]
Note that I'm not entirely sure if this is just an outdated angularism or not.

**Comment by zoechi** [comment]
I'm pretty sure this is from the time when Angular2 templates weren't yet case-sensitive.
I don't think auto-converson should happen. One can always use `@Input('is-sleeping') bool isSleeping;` if such a property name is desired.

https://github.com/angular/angular/blob/master/CHANGELOG.md#200-alpha52-2015-12-10

**Comment by MichaelRFairhurst** [comment]
Ah fantastic. Thanks for finding the proper changelog too.

I was not sure if this was just outdated code and was going to triage that, but looks like here's all the proof we need!

closing this.
