### ISSUE TITLE
"keyup" event on input tag not working

### ISSUE THREAD

**Issue by MichaelRFairhurst** [dart-lang/angular_analyzer_plugin#77]
I think its because the dart:html event doesn't begin with "on" and we are stripping it, but it could be some other reason.

```<input (keyup)="code" />```

getting error "the bound output does not exist on any directives"

**Comment by MichaelRFairhurst** [comment]
Also seems to be an issue with mouseenter and mouseleave

**Comment by zoechi** [comment]
> the bound output does not exist on any directives"

I think it just shouldn't expect DOM events being exposed as outputs

**Comment by MichaelRFairhurst** [comment]
It doesn't yet get to the point of recognizing this as a DOM event. Anything that isn't a DOM event it expects to be an output, and so that's why it complains about the output errors.

Turns out in dart:html, the event is described like so:

```
    @DomAttribute("onkeyup")
    ElementStream<KeyEvent> get onKeyUp() {
```

We analyze that, but a subtly wrong way. We take the method name and lop off the "on" and decapitalize it to get "keyUp." Therefore

```<input (keyUp)="code" />```

works just fine.

The solution is to analyze the `@DomAttribute` annotation instead of the method name.

**Comment by MichaelRFairhurst** [comment]
Merge PR #80
