### ISSUE TITLE
Support (but probably also lint) the uncommonly-used typescript map key syntax, which doesn't require quotes.

### ISSUE THREAD

**Issue by MichaelRFairhurst** [dart-lang/angular_analyzer_plugin#78]
Seeing in this project: https://github.com/daftspaniel

the code `<textarea [ngStyle]="{width: showPreview ? '48%':'99%'}"`

Getting the error "Undefined name width."

Does this work in angular? We can probably tinker with the AST that the parser produces to turn these into string literals. Or maybe there's a problem with the way we call the parser.

**Comment by scheglov** [comment]
Well, from the Dart parser and resolver point of view the warning is correct.
Without quotes `width` means an identifier, so we try to resolve it and... it's not defined.

**Comment by MichaelRFairhurst** [comment]
This might even only be valid in an outdated version of angular...

**Comment by MichaelRFairhurst** [comment]
Confirmed that this works on angular 2.0.0, but perhaps I should file this as a bug with them...after all, someone may want to create a `Map<InputElement, String>` or something in a dart angular template expression and this must be impossible based on how its handling this.

**Comment by zoechi** [comment]
This is TS semantics. I'd prefer it to behave like its common in Dart (just my personl opinion)

**Comment by TedSander** [comment]
Just FYI this would require an internal cleanup. There is code that uses this syntax.

I agree with making it more Darty.

**Comment by zoechi** [comment]
First introduce the linter rule, then later change the semantics.

The template syntax is kept equal between Dart and TS (like `let`) but the expression language is quite different anyway, so I don't think there is a reason to keep TS semantics (except for preventing breaking changes of course until the next major version)

**Comment by MichaelRFairhurst** [comment]
I'm going to lower this to a P2, and change from "bug" to enhancement.

Seems like very few people run into this issue -- perhaps few enough, that we _want_ an analysis error, to nudge the few towards the darty syntax. 

Therefore its a P2 enhancement to support the few who use typescript syntax, which we probably want to treat as a lint error anyway.

**Comment by MichaelRFairhurst** [comment]
No plans to do this. Angular will soon use dart syntax only, too.
