### ISSUE TITLE
Hint about implicit boolean return

### ISSUE THREAD

**Issue by zoechi** [dart-lang/angular_analyzer_plugin#99]
In this case

    <div (click)="prop = $event"

when `$event` is `false`, `$event.preventDefault()` is called
or when `myHandler()`

    <div (click)="myHandler()"

returns `false`

The former doesn't look intentional, for the later it's unclear.

It's just an idea that some checks might be helpful, I'm not sure there is a good solution.

**Comment by MichaelRFairhurst** [comment]
Great idea for the types of things we could catch.

Is there a best way to do this? Maybe using 'return' is accepted here or something?

We could definitely check if the expression is of type 'bool', the question would be what to do with it. If there's a best way to prevent default, we can warn of boolean expressions that don't follow that best way. If not, we have to get a bit more creative.

We could definitely check for value by assignment as a lint error. `shown = false` calling `preventDefault` is a pretty good lint. (note reporting this lint for `shown = true` would be annoying).

For some of the less clear cut but still possibly unintentional spots like `myHandler()`, the idea comes to mind that maybe we could color the expression in a certain way. The server has a 'getHighlights' function, but it may take doing some work on the intellij plugin to make it really work well.

**Comment by zoechi** [comment]
I don't think there is a "good" way that can be distinguished. 
Highlighting sounds interesting.

**Comment by zoechi** [comment]
This is deprecated #dart-lang/angular2#387
